### ISSUE TITLE
Gracefully handle case where there is no image chooser app

### ISSUE THREAD

**Issue by joekir** [freeotp/freeotp-android#154]
On a device with no gallery app enabled, the app will crash if you click to update the token icon.
We should more gracefully describe to the user why this issue is occurring, and not crash.

Example error in adb logs:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.fedorahosted.freeotp, PID: 6009
                  android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.PICK dat=content://media/external/images/media }
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
                      at android.app.Activity.startActivityForResult(Activity.java:3930)
                      at android.app.Activity.startActivityForResult(Activity.java:3890)
                      at org.fedorahosted.freeotp.edit.EditActivity.onClick(EditActivity.java:141)
                      at android.view.View.performClick(View.java:5204)
                      at android.view.View$PerformClick.run(View.java:21153)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by max-wittig** [comment]
Should be fixed in https://github.com/freeotp/freeotp-android/commit/78b3803925298482c8b77498d6a5a32fae9aaee8  
Please try again

**Comment by joekir** [comment]
Will do, thanks

**Comment by joekir** [comment]
Yes that fixed the issue, nice one @max-wittig!
